cmake_minimum_required(VERSION 3.10)

# Flock
# add_executable(tests_flock tests.cpp flock_t.cpp)
# target_link_libraries(tests_flock PUBLIC flock)
# target_include_directories(tests_flock PUBLIC ../ext)

# allow user to run tests with `make test` or `ctest`
# include(../cmake/Catch.cmake)
# catch_discover_tests(tests_flock)
